# setup
on:
    push:
    # supplies a button in gh for manual running
    workflow_dispatch:
    # when to run the file
    schedule:
        - cron:  '0 16 * * *' # every day at 4pm UTC

# lets gh change files
permissions: 
    contents: write

# what to do when running the code
jobs:
    run:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: development
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
            
            # Check the counter
            - name: Get counter value
              id: get-counter
              run: echo "::set-output name=value::$(cat counter.txt)"
              
            # If counter > 10, stop the job
            - name: Check if counter exceeds 10
              run: if [[ "${{ steps.get-counter.outputs.value }}" -gt 10 ]]; then exit 78; fi
            
            # Run your main logic
            - run: python "BBC scraper.py" > data/$(date +%Y%m%d-%H%M%S).txt
            
            # Increment and commit the counter
            - run: |-
                  echo $(( ${steps.get-counter.outputs.value} + 1 )) > counter.txt
                  
                  git config user.name 'GitHub Actions'
                  git config user.email 'actions@users.noreply.github.com'
                  
                  git add -A
                  git commit -m 'Increment counter' || exit 0
                  git push
